version: "3"
services:
  api:
    build: .
    container_name: api
    restart: always
    env_file:
     - .env
    ports:
       - ${SERVER_PORT_DC}:${SERVER_PORT_DC}
    volumes:
      - .:/src
    working_dir: /src
    command: yarn dev
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

#   api_2:
#     image: node:latest
#     container_name: api_2
#     restart: always
#     depends_on: 
#       - api
#     env_file:
#      - .env
#     ports:
#       - ${SERVER_PORT2}:${SERVER_PORT2}
#     volumes:
#       - .:/src
#     working_dir: /src
#     command: npm start
#     logging:
#       driver: "json-file"
#       options:
#         max-size: "10m"
#         max-file: "5"